### ISSUE TITLE
**Class for a standardized log**

### ISSUE THREAD

**Issue by MunsMan** [MunsMan/Platform#3]
The goal is to create an easy debugging for the Platform. It should be logged:
1. *with every entry*
- timestamp
- type of entry
2. connection quality
- connecting
- disconnecting
3. data exchange
- origin and destination
- type and size

**Tasks**
- [x] creating the object specific log file 
- [x] writing the log-head
- [x] standardized entries
- [ ] set log-size limit

Generell Information about the service
All the logs will be saved in an object-specific text-file of type .txt. So that every specific object can be watched separately. The log will be limited to a given number of entries, so that is won't fill up the hard drive.

**Comment by MunsMan** [comment]
First two parts are already integrated. We are only missing the log-size limit.

**Comment by MunsMan** [comment]
Adding to the Issue:

- [ ] adding, that the log is writing by standard into a bucket
